---
- name: Purge dnf cache files
  ansible.builtin.command: "dnf clean all"
  register: result
  changed_when: "'0 files removed' not in result.stdout"
  retries: "{{ os_update_retry }}"
  delay: "{{ os_update_retry_delay }}"
  until: result is not failed

- name: print results
  debug:
    var: result
  when: os_update_debug_vars

- name: install needed packages
  dnf:
    name:
    - yum-utils
    - python3-dnf
    state: present
  register: result
  retries: "{{ os_update_retry }}"
  delay: "{{ os_update_retry_delay }}"
  until: result is not failed

- name: print results
  debug:
    var: result
  when: os_update_debug_vars

- name: perform full os upgrade
  dnf:
    name: '*'
    update_cache: true
    state: latest
  register: result
  retries: "{{ os_update_retry }}"
  delay: "{{ os_update_retry_delay }}"
  until: result is not failed

- name: print results
  debug:
    var: result
  when: os_update_debug_vars

...
