---
- name: EOL message
  debug:
    msg:
    - "RHEL 8 based OS have only python3.6 base support"
    - "       So dnf and other modules will fail with ansible core >= 2.16"
    - "       We workaround with shell cmd to provide working tasks for rhel8"
    - "       https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html"
    - "       https://github.com/ansible/ansible/issues/83357#issuecomment-2150254754"

- name: Purge dnf cache files
  ansible.builtin.command: "dnf clean all"
  register: result
  changed_when: "'0 files removed' not in result.stdout"
  retries: "{{ os_update_retry }}"
  delay: "{{ os_update_retry_delay }}"
  until: result is not failed

- name: print results
  debug:
    var: result
  when: os_update_debug_vars

- name: Install required packages if not already installed (dnf)
  ansible.builtin.command: "dnf -y install python3-dnf yum-utils"
  register: result
  changed_when: "'Nothing to do.' not in result.stdout"
  retries: "{{ os_update_retry }}"
  delay: "{{ os_update_retry_delay }}"
  until: result is not failed

- name: print results
  debug:
    var: result
  when: os_update_debug_vars

- name: Install all updates (dnf)
  ansible.builtin.command: "dnf -y update "
  register: result
  changed_when: "'Nothing to do.' not in result.stdout"
  retries: "{{ os_update_retry }}"
  delay: "{{ os_update_retry_delay }}"
  until: result is not failed

- name: print results
  debug:
    var: result
  when: os_update_debug_vars
...
