---
- name: perform full os upgrade
  yum:
    name: '*'
    update_cache: true
    state: latest
  register: result
  retries: "{{ os_update_retry }}"
  delay: "{{ os_update_retry_delay }}"
  until: result is not failed
- name: print results
  debug:
    var: result
  when: os_update_debug_vars

...
