---
- name: Check if a reboot is needed for Debian and Ubuntu boxes
  stat: 
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot Debian like server
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
  throttle: "{{ os_update_conc_reboot }}"
  when: reboot_required_file.stat.exists or os_update_reboot == 'force'

...
