---
- name: Check for reboot hint
  shell: |
    MISSING_EXECUTEABLES_COUNT=`cat /proc/*/smaps | sed  '/\//!d;/\(deleted\)/!d;/ \/\[/d;/ \/SYSV/d;/ \/dev\/zero/d;s@.* /@/@' | sort -u | wc -l`
    INITRD_FILE=`cat /proc/cmdline | sed 's/BOOT_IMAGE=/\/boot\//;s/ .*//'`
    INITRD_MOD_EPOCH=`stat -c '%Y' $INITRD_FILE`
    LAST_REBOOT_EPOCH=`stat -c '%Y' /var/log/dmesg`
    if [ $MISSING_EXECUTEABLES_COUNT -gt 0 ] ; then 
      echo "WARNING: Some processes have missing files: system needs a reboot"
    fi
    if [ $INITRD_MOD_EPOCH -gt $LAST_REBOOT_EPOCH ] ; then
      echo "WARNING: New Kernel found: system needs a reboot"
    fi
    echo "DEBUG: MISSING_EXECUTEABLES_COUNT=$MISSING_EXECUTEABLES_COUNT INITRD_FILE=$INITRD_FILE INITRD_MOD_EPOCH=$INITRD_MOD_EPOCH LAST_REBOOT_EPOCH=$LAST_REBOOT_EPOCH"
  ignore_errors: true
  changed_when: false
  register: reboot_hint

- name: show cmd output
  debug: var=reboot_hint
  when: os_update_debug_vars

- name: reboot host if needed
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
  throttle: "{{ os_update_conc_reboot }}"
  when: >
    reboot_hint.stdout.find("reboot") != -1 or
    os_update_reboot == 'force'
...
