---
- name: install needed packages
  yum: 
    name:
      - yum-plugin-security
      - yum-utils
  register: result
  retries: "{{ os_update_retry }}"
  delay: "{{ os_update_retry_delay }}"
  until: result is not failed
- name: print results
  debug:
    var: result
  when: os_update_debug_vars

- name: install security patches with yum
  yum:
    name: '*'
    update_cache: true
    state: latest
    security: true
  register: result
  retries: "{{ os_update_retry }}"
  delay: "{{ os_update_retry_delay }}"
  until: result is not failed
- name: print results
  debug:
    var: result
  when: os_update_debug_vars

...
