---
- name: Install security updates
  shell: |
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    sudo apt-get -y install --only-upgrade $(apt list --upgradable 2>/dev/null | grep -i "\-security" | awk -F/ '{print $1}')
  changed_when: false
  register: result
  retries: "{{ os_update_retry }}"
  delay: "{{ os_update_retry_delay }}"
  until: result is not failed

- name: print results
  debug:
    var: result
  when: os_update_debug_vars

- name: check for installed packages
  debug: msg='updates got installed'
  when: result.stdout.find('0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded') == -1
...
