---
- name: apply security windows updates
  win_updates:
    category_names: "{{ os_update_windows_updates_category_names_security }}"
    reboot: "{{ os_update_reboot }}"
    reject_list: "{{ os_update_windows_updates_reject_list }}"
  register: result
  retries: "{{ os_update_retry }}"
  delay: "{{ os_update_retry_delay }}"
  until: result is not failed
- name: print results
  debug:
    var: result
  when: os_update_debug_vars

...
